FROM node:18-buster-slim as builder
RUN apt-get update -y

WORKDIR /app
COPY package*.json yarn.lock tsconfig.json vite.config.js sw.js *.d.ts ./

# following needs to be copied before installing dependencies as it gets called postinstall
COPY scripts/patchReactVirtualized.js scripts/

RUN yarn --quiet && yarn install

COPY nginx/ nginx/
COPY assets/ assets/
COPY locale/ locale/
COPY scripts/ scripts/
COPY schema.graphql ./
COPY introspection.json ./
COPY introspection*.json ./
COPY .featureFlags/ ./.featureFlags/

COPY src/ src/

ARG API_URI
ARG APP_MOUNT_URI
ARG APPS_MARKETPLACE_API_URI
ARG APPS_TUNNEL_URL_KEYWORDS
ARG STATIC_URL
ARG SKIP_SOURCEMAPS

ENV API_URI ${API_URI:-http://localhost:8000/graphql/}
ENV APP_MOUNT_URI ${APP_MOUNT_URI:-/dashboard/}
ENV APPS_MARKETPLACE_API_URI ${APPS_MARKETPLACE_API_URI:-https://apps.saleor.io/api/v2/saleor-apps}
ENV APPS_TUNNEL_URL_KEYWORDS ${APPS_TUNNEL_URL_KEYWORDS}
ENV STATIC_URL ${STATIC_URL:-/dashboard/}
ENV SKIP_SOURCEMAPS ${SKIP_SOURCEMAPS:-true}

RUN yarn --quiet && yarn build

FROM nginx:stable-buster as runner
RUN apt-get update && apt-get -y upgrade

WORKDIR /app

# ENV VARS SHOULD BE PASSED IN FROM Deployment YAML
# Assume they will override what was set at build time

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/replace-api-url.sh /docker-entrypoint.d/50-replace-api-url.sh
COPY --from=builder /app/build/ /app/

EXPOSE 9000
